package com.bankingplatform.opsagent.service;

import com.bankingplatform.opsagent.llm.LlmDecision;
import com.bankingplatform.opsagent.model.AgentReport;
import com.bankingplatform.opsagent.model.Incident;
import com.bankingplatform.opsagent.model.MitigationAction;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.List;

@Component
public class ReportBuilder {

    public AgentReport build(Incident incident, LlmDecision decision) {
        AgentReport report = new AgentReport();
        report.setIncidentId(incident.getId());
        report.setTitle(incident.getTitle());
        report.setSeverity(incident.getSeverity() == null ? null : incident.getSeverity().name());
        report.setAffectedService(incident.getAffectedService());
        report.setStatus(incident.getStatus() == null ? null : incident.getStatus().name());
        report.setExecutiveSummary(decision.getRootCauseHypothesis() != null
            ? decision.getRootCauseHypothesis()
            : incident.getSummary());
        report.setRootCauseHypothesis(decision.getRootCauseHypothesis());
        report.setFindings(new ArrayList<>(decision.getFindings()));
        report.setRecommendedActions(decision.getRecommendedActions().isEmpty()
            ? incident.getMitigations().stream().map(MitigationAction::getDescription).toList()
            : new ArrayList<>(decision.getRecommendedActions()));
        report.setResiliencyNotes(new ArrayList<>(decision.getResiliencyNotes()));
        report.setEvidence(incident.getEvidence());

        String markdown = decision.getFinalAnswer();
        if (markdown == null || markdown.isBlank()) {
            markdown = renderMarkdown(report, incident);
        }
        report.setMarkdown(markdown);
        return report;
    }

    private String renderMarkdown(AgentReport report, Incident incident) {
        StringBuilder sb = new StringBuilder();
        sb.append("# Incident Report: ").append(nullToEmpty(report.getTitle())).append("\n\n");
        sb.append("- **Incident ID**: ").append(report.getIncidentId()).append("\n");
        sb.append("- **Severity**: ").append(report.getSeverity()).append("\n");
        sb.append("- **Status**: ").append(report.getStatus()).append("\n");
        sb.append("- **Affected service**: ").append(report.getAffectedService()).append("\n\n");
        sb.append("## Executive summary\n")
            .append(nullToEmpty(report.getExecutiveSummary())).append("\n\n");
        sb.append("## Findings\n");
        appendBullets(sb, report.getFindings());
        sb.append("\n## Recommended mitigation\n");
        appendBullets(sb, report.getRecommendedActions());
        sb.append("\n## Resiliency notes\n");
        appendBullets(sb, report.getResiliencyNotes());
        if (!incident.getSteps().isEmpty()) {
            sb.append("\n## Investigation timeline\n");
            incident.getSteps().forEach(step ->
                sb.append("- `").append(step.getTool()).append("`: ").append(step.getResultSummary()).append("\n"));
        }
        sb.append("\n---\n_Generated by banking-platform ops-agent._\n");
        return sb.toString();
    }

    private void appendBullets(StringBuilder sb, List<String> items) {
        if (items == null || items.isEmpty()) {
            sb.append("- (none)\n");
            return;
        }
        for (String item : items) {
            sb.append("- ").append(item).append("\n");
        }
    }

    private String nullToEmpty(String s) {
        return s == null ? "" : s;
    }
}
